---
# - include_tasks : install-setup.yaml
# - include_tasks : kind-cluster.yaml
- include_tasks : backend-aspdotnet.yaml
# - include_tasks : install-haproxy-ingress.yaml
# - include_tasks : database-mssql.yaml