apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-sql-docker-app
  namespace: myapp
  labels:
    app: ms-sql-docker-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-sql-docker-app
  template:
    metadata:
      labels:
        app: ms-sql-docker-app
    spec:
      containers:
        - name: ms-sql-docker-app
          image: mcr.microsoft.com/mssql/server:2022-latest
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_SA_PASSWORD
              value: "Your_password123!"
---
apiVersion: v1
kind: Service
metadata:
  name: ms-sql-docker-app
  namespace: myapp
spec:
  selector:
    app: ms-sql-docker-app
  ports:
    - port: 1433
      targetPort: 1433
  type: ClusterIP
